global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - nextmonitor-prometheus:9090

  - job_name: nextlife-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - next-gateway:8081
          - next-core-service:8090
          - next-role-service:8091
          - next-log-service:8092
          - next-data-service:8093
          - next-flow-service:8094
